from __future__ import annotations

from collections import deque
from datetime import datetime
import json
import logging
import os
from pathlib import Path
import re
import sqlite3
import subprocess
import tempfile
import tomllib
from typing import Iterable

import yaml

from .chunking import chunk_text, content_hash, frontmatter, markdown_title, stable_id
from .config import Settings
from .models import Document, SourceConfig

logger = logging.getLogger(__name__)


def _safe_resolve(path: Path, root: Path) -> Path:
    resolved = path.resolve()
    resolved.relative_to(root.resolve())
    return resolved


def _skill_id(source: SourceConfig, path: Path) -> str:
    relative = path.relative_to(source.path).as_posix()
    suffix = relative[:-9].strip("/") if relative.endswith("/SKILL.md") else relative
    suffix = suffix or source.name
    return f"{source.name}:{suffix}"


def _iter_skill_paths(root: Path) -> Iterable[Path]:
    """Yield logical skill files, including explicitly linked skill directories.

    ``Path.rglob`` includes a symlinked ``SKILL.md`` file but does not descend
    into a symlinked skill directory. Hermes and several native integrations
    install skills using the latter form. Follow only a linked directory whose
    own top level contains ``SKILL.md``; never recursively walk an arbitrary
    external tree.
    """
    excluded = {".git", ".archive", ".retrieval-archive", "node_modules", ".venv"}
    selected = {
        path.absolute()
        for path in root.rglob("SKILL.md")
        if not any(
            part in excluded
            for part in path.relative_to(root).parts
        )
    }
    for directory in root.rglob("*"):
        if not directory.is_symlink():
            continue
        logical_path = (directory / "SKILL.md").absolute()
        if any(
            part in excluded
            for part in logical_path.relative_to(root.absolute()).parts
        ):
            continue
        if logical_path.resolve().is_file():
            selected.add(logical_path)
    yield from sorted(selected)


def _descriptor_text(
    text: str,
    *,
    title: str,
    description: str,
    max_chars: int = 5000,
) -> str:
    """Build one compact semantic card instead of embedding whole skill bodies."""

    body = text
    if body.startswith("---\n"):
        end = body.find("\n---", 4)
        if end >= 0:
            body = body[end + 4 :]
    headings = [
        match.group(1).strip()
        for match in re.finditer(r"(?m)^#{1,4}\s+(.+?)\s*$", body)
    ][:20]
    paragraphs = []
    for block in re.split(r"\n\s*\n", body):
        clean = re.sub(r"\s+", " ", block).strip()
        if not clean or clean.startswith(("#", "```")):
            continue
        # Descriptor cards are search material, not a copy of the source
        # graph. Remove link syntax so IWE sees only links generated by the
        # catalog itself; labels remain lexical evidence.
        clean = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", clean)
        clean = re.sub(r"\[\[([^\]]+)\]\]", r"\1", clean)
        clean = re.sub(r"<[^>]+>", "", clean)
        paragraphs.append(clean)
        if sum(len(item) for item in paragraphs) >= 1800:
            break
    parts = [f"Skill: {title}"]
    if description:
        parts.append(f"Purpose: {description}")
    if headings:
        parts.append("Topics: " + "; ".join(headings))
    if paragraphs:
        parts.append("Synopsis: " + " ".join(paragraphs))
    return "\n".join(parts)[:max_chars]


def _frontmatter_payload(text: str) -> dict[str, object]:
    """Read typed skill metadata without changing the legacy string parser."""

    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end < 0:
        return {}
    try:
        payload = yaml.safe_load(text[4:end]) or {}
    except yaml.YAMLError:
        return {}
    return payload if isinstance(payload, dict) else {}


def _truthy(value: object) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().casefold() in {"1", "true", "yes", "on"}
    return False


def _skill_state(source: SourceConfig, text: str) -> str:
    """Promote OMP-hidden skills out of an otherwise native source.

    OMP normalizes Agent Skills' ``disable-model-invocation`` field to
    ``disableModelInvocation``. Accept both spellings so Retrieval agrees with
    either authored form while leaving cold and archived source policy intact.
    """

    if source.state != "native":
        return source.state
    payload = _frontmatter_payload(text)
    if any(
        _truthy(payload.get(key))
        for key in ("hide", "disableModelInvocation", "disable-model-invocation")
    ):
        return "hidden"
    return "native"


def iter_skills(source: SourceConfig) -> Iterable[Document]:
    for path in _iter_skill_paths(source.path):
        logical_path = path.absolute()
        canonical_path = path.resolve()
        if not canonical_path.is_file():
            logger.warning("skipping broken skill link: %s", logical_path)
            continue
        text = canonical_path.read_text(encoding="utf-8", errors="replace")
        meta = frontmatter(text)
        skill_id = _skill_id(source, logical_path)
        title = meta.get("name") or markdown_title(
            text,
            logical_path.parent.name or source.name,
        )
        description = (meta.get("description") or "").strip()[:1000]
        state = _skill_state(source, text)
        relative = logical_path.relative_to(source.path).as_posix()
        descriptor = _descriptor_text(
            text,
            title=title,
            description=description,
        )
        yield Document(
            # Retain the former first-chunk ID so an upgrade replaces that
            # record and garbage-collects the remaining body chunks.
            record_id=stable_id(source.kind, source.name, relative, 0),
            source_name=source.name,
            kind=source.kind,
            title=title,
            content=descriptor,
            locator=str(canonical_path),
            metadata={
                "skill_id": skill_id,
                "description": description,
                "relative_path": relative,
                "state": state,
                "native_harness": source.harness,
                "descriptor_version": 2,
                "content_hash": content_hash(descriptor),
            },
        )


_REFERENCE_EXCLUDES = {
    ".git",
    ".iwe",
    ".venv",
    "node_modules",
    "dist",
    "build",
}
_HEADING = re.compile(r"(?m)^(#{1,6})\s+(.+?)\s*$")


def _reference_sections(text: str, fallback: str) -> list[tuple[int, str, str]]:
    """Split Markdown on headings while preserving useful preamble text."""

    matches = list(_HEADING.finditer(text))
    sections: list[tuple[int, str, str]] = []
    if not matches:
        clean = text.strip()
        return [(0, fallback, clean)] if clean else []
    preamble = text[: matches[0].start()].strip()
    if preamble:
        sections.append((0, fallback, preamble))
    for position, match in enumerate(matches):
        end = matches[position + 1].start() if position + 1 < len(matches) else len(text)
        heading = match.group(2).strip()
        content = text[match.start() : end].strip()
        if content:
            sections.append((position + 1, heading, content))
    return sections


def iter_references(source: SourceConfig) -> Iterable[Document]:
    """Yield one bounded, addressable document per Markdown heading."""

    for path in sorted(source.path.rglob("*.md")):
        if not path.is_file() or any(part in _REFERENCE_EXCLUDES for part in path.parts):
            continue
        canonical = _safe_resolve(path, source.path)
        text = canonical.read_text(encoding="utf-8", errors="replace")
        relative = canonical.relative_to(source.path.resolve()).as_posix()
        file_title = markdown_title(text, canonical.stem)
        for section_index, heading, content in _reference_sections(text, file_title):
            item_id = f"{source.name}:{relative}#{section_index}"
            descriptor = content[:12000]
            yield Document(
                record_id=stable_id(source.kind, source.name, relative, section_index),
                source_name=source.name,
                kind=source.kind,
                title=f"{file_title} · {heading}" if heading != file_title else file_title,
                content=descriptor,
                locator=str(canonical),
                metadata={
                    "reference_id": item_id,
                    "relative_path": relative,
                    "heading": heading,
                    "section_index": section_index,
                    "state": source.state,
                    "content_hash": content_hash(descriptor),
                },
            )


def read_reference_section(
    path: Path,
    section_index: int,
    *,
    expected_heading: str = "",
) -> str:
    """Read one previously indexed section without rescanning its source tree."""

    text = path.read_text(encoding="utf-8", errors="replace")
    fallback = markdown_title(text, path.stem)
    for position, heading, content in _reference_sections(text, fallback):
        if position == section_index:
            if expected_heading and heading != expected_heading:
                raise ValueError(
                    "reference index is stale; heading changed from "
                    f"{expected_heading!r} to {heading!r}"
                )
            return content
    raise ValueError(f"reference section no longer exists: {path}#{section_index}")


_WORKFLOW_DIRECTORIES = {
    "agents": "agent",
    "commands": "command",
    "hooks": "hook",
}
_WORKFLOW_SUFFIXES = {
    ".bash",
    ".json",
    ".md",
    ".sh",
    ".toml",
    ".yaml",
    ".yml",
}


def _is_workflow_file(path: Path) -> bool:
    return (
        path.is_file()
        and path.suffix.lower() in _WORKFLOW_SUFFIXES
        and not path.name.endswith(("-test.sh", "_test.sh"))
        and not any(part in {".git", "node_modules", ".venv"} for part in path.parts)
    )


def _workflow_id(source: SourceConfig, path: Path) -> str:
    relative = path.relative_to(source.path).as_posix()
    return f"{source.name}:{relative}"


def _workflow_description(path: Path, text: str, workflow_type: str) -> str:
    if path.suffix.lower() == ".md":
        description = frontmatter(text).get("description", "").strip()
        if description:
            return description[:1000]
    elif path.suffix.lower() == ".toml":
        try:
            description = str(tomllib.loads(text).get("description") or "").strip()
        except tomllib.TOMLDecodeError:
            description = ""
        if description:
            return description[:1000]
    for raw in text.splitlines():
        line = raw.strip().lstrip("#").strip()
        if line and not line.startswith(("!", "{", "[")):
            return line[:1000]
    return f"{workflow_type.title()} definition: {path.stem.replace('-', ' ')}"


def iter_workflows(source: SourceConfig) -> Iterable[Document]:
    """Index opt-in personas, commands, and hooks without activating them."""
    for directory, workflow_type in _WORKFLOW_DIRECTORIES.items():
        root = source.path / directory
        if not root.is_dir():
            continue
        for path in sorted(root.rglob("*")):
            if not _is_workflow_file(path):
                continue
            path = _safe_resolve(path, source.path)
            text = path.read_text(encoding="utf-8", errors="replace")
            relative = path.relative_to(source.path).as_posix()
            workflow_id = _workflow_id(source, path)
            title = (
                frontmatter(text).get("name")
                if path.suffix.lower() == ".md"
                else ""
            ) or path.stem.replace("-", " ")
            description = _workflow_description(path, text, workflow_type)
            descriptor = _descriptor_text(
                text,
                title=title,
                description=description,
            )
            yield Document(
                record_id=stable_id(source.kind, source.name, relative, 0),
                source_name=source.name,
                kind=source.kind,
                title=title,
                content=descriptor,
                locator=str(path),
                metadata={
                    "workflow_id": workflow_id,
                    "workflow_type": workflow_type,
                    "description": description,
                    "relative_path": relative,
                    "state": source.state,
                    "descriptor_version": 2,
                    "content_hash": content_hash(descriptor),
                },
            )


def iter_context_mode(source: SourceConfig) -> Iterable[Document]:
    for database in sorted(source.path.glob("*.db")):
        connection = sqlite3.connect(f"file:{database}?mode=ro", uri=True, timeout=5)
        try:
            query = """
                SELECT c.rowid, c.title, c.content, c.source_id, c.content_type,
                       c.source_category, c.session_id, c.event_id, c.timestamp,
                       s.label, s.file_path, s.content_hash
                  FROM chunks AS c
             LEFT JOIN sources AS s ON s.id = c.source_id
              ORDER BY c.rowid
            """
            for row in connection.execute(query):
                (
                    rowid, title, content, source_id, content_type, source_category,
                    session_id, event_id, timestamp, label, file_path, source_hash,
                ) = row
                text = str(content or "").strip()
                if not text:
                    continue
                canonical = f"{database.name}:{rowid}"
                locator = str(file_path or f"{database}#rowid={rowid}")
                for index, piece in chunk_text(text):
                    yield Document(
                        record_id=stable_id(
                            source.kind,
                            source.name,
                            canonical,
                            index,
                            content_hash(piece),
                        ),
                        source_name=source.name,
                        kind=source.kind,
                        title=str(title or label or "context-mode chunk"),
                        content=piece,
                        locator=locator,
                        metadata={
                            "database": database.name,
                            "rowid": int(rowid),
                            "source_id": int(source_id or 0),
                            "content_type": str(content_type or ""),
                            "source_category": str(source_category or ""),
                            "session_id": str(session_id or ""),
                            "event_id": str(event_id or ""),
                            "timestamp": str(timestamp or ""),
                            "source_hash": str(source_hash or ""),
                            "chunk_index": index,
                            "content_hash": content_hash(piece),
                        },
                    )
        finally:
            connection.close()


def _hermes_session_homes(source: SourceConfig) -> list[tuple[str, Path]]:
    """Return the default Hermes home and every locally stored named profile."""
    homes = [("default", source.path)]
    profiles = source.path / "profiles"
    if not profiles.is_dir():
        return homes
    for profile_home in sorted(profiles.iterdir(), key=lambda path: path.name):
        if (
            profile_home.is_dir()
            and not profile_home.is_symlink()
            and (
                (profile_home / "state.db").is_file()
                or (profile_home / "sessions" / "sessions.json").is_file()
            )
        ):
            homes.append((profile_home.name, profile_home))
    return homes


def _context_mode_metrics(
    profile_home: Path,
) -> tuple[dict[str, dict[str, object]], dict[tuple[str, str], deque[dict[str, object]]]]:
    """Load small linkage metadata from Hermes' context-mode plugin, if present."""
    database = profile_home / "plugins" / "hermes-context-mode" / "metrics.db"
    if not database.is_file():
        return {}, {}
    connection = sqlite3.connect(
        f"file:{database}?mode=ro",
        uri=True,
        timeout=5,
    )
    connection.row_factory = sqlite3.Row
    try:
        summaries = {
            str(row["session_id"]): dict(row)
            for row in connection.execute(
                """
                SELECT session_id, platform, model, started, ended, tool_calls,
                       bytes_saved, tools_saved, blocks
                  FROM session_metrics
                """
            )
        }
        savings: dict[tuple[str, str], deque[dict[str, object]]] = {}
        for row in connection.execute(
            """
            SELECT id, session_id, tool_name, original_bytes, saved_bytes,
                   sandbox_path, ts
              FROM tool_savings
          ORDER BY id
            """
        ):
            key = (
                str(row["session_id"] or ""),
                str(row["tool_name"] or ""),
            )
            saving = dict(row)
            try:
                saving["_epoch"] = datetime.fromisoformat(
                    str(row["ts"]).replace("Z", "+00:00")
                ).timestamp()
            except (TypeError, ValueError):
                saving["_epoch"] = 0.0
            savings.setdefault(key, deque()).append(saving)
        return summaries, savings
    except sqlite3.OperationalError as exc:
        logger.warning("Context-mode metrics are unavailable at %s: %s", database, exc)
        return {}, {}
    finally:
        connection.close()


def _serialized_tool_calls(message: dict[str, object]) -> str:
    value = message.get("tool_calls")
    if not value:
        return ""
    if isinstance(value, str):
        return value
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True)
    except (TypeError, ValueError):
        return str(value)


def _take_context_saving(
    savings: dict[tuple[str, str], deque[dict[str, object]]],
    session_id: str,
    tool_name: str,
    message_timestamp: float,
) -> dict[str, object] | None:
    linked = savings.get((session_id, tool_name))
    if not linked or not message_timestamp:
        return None
    # The plugin and Hermes state database use different IDs, but both record
    # wall-clock time. Link only a close event; never assign the next saving to
    # an unrelated earlier call merely because its tool name matches.
    while linked and float(linked[0].get("_epoch") or 0) < message_timestamp - 30:
        linked.popleft()
    if (
        linked
        and abs(float(linked[0].get("_epoch") or 0) - message_timestamp) <= 30
    ):
        return linked.popleft()
    return None


def iter_hermes_sessions(source: SourceConfig, settings: Settings) -> Iterable[Document]:
    # Explicitly scope each export. Both the default and Librarian MCP servers
    # can host Retrieval, so inheriting that process's HERMES_HOME would make
    # watcher leadership nondeterministically omit the other profile.
    for profile_name, profile_home in _hermes_session_homes(source):
        session_metrics, tool_savings = _context_mode_metrics(profile_home)
        with tempfile.NamedTemporaryFile(
            prefix=f"hermes-retrieval-{profile_name}-",
            suffix=".jsonl",
            delete=False,
        ) as handle:
            export_path = Path(handle.name)
        try:
            command = [
                settings.hermes_command,
                "sessions",
                "export",
                str(export_path),
                "--format",
                "jsonl",
                "--redact",
                "--yes",
                "--min-messages",
                "1",
            ]
            if settings.hermes_session_newer_than:
                command.extend(["--newer-than", settings.hermes_session_newer_than])
            environment = os.environ.copy()
            environment["HERMES_HOME"] = str(profile_home)
            if profile_name == "default":
                environment.pop("HERMES_PROFILE", None)
            else:
                environment["HERMES_PROFILE"] = profile_name
            result = subprocess.run(
                command,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                timeout=300,
                check=False,
                env=environment,
            )
            if result.returncode:
                raise RuntimeError(
                    "Hermes export failed for profile "
                    f"{profile_name!r} ({result.returncode}): "
                    f"{result.stderr[-1000:]}"
                )
            with export_path.open(encoding="utf-8") as rows:
                for raw in rows:
                    if not raw.strip():
                        continue
                    session = json.loads(raw)
                    session_id = str(session.get("id") or "")
                    title = str(session.get("title") or "Hermes session")
                    metrics = session_metrics.get(session_id, {})
                    for position, message in enumerate(session.get("messages") or []):
                        role = str(message.get("role") or "")
                        if role not in {"user", "assistant", "tool"}:
                            continue
                        raw_content = message.get("content")
                        if isinstance(raw_content, str):
                            text = raw_content.strip()
                        elif raw_content:
                            try:
                                text = json.dumps(
                                    raw_content,
                                    ensure_ascii=False,
                                    sort_keys=True,
                                )
                            except (TypeError, ValueError):
                                text = str(raw_content)
                        else:
                            text = ""
                        tool_calls = _serialized_tool_calls(message)
                        # Preserve the assistant-side call event even when it
                        # has no prose content. Otherwise the exact call/result
                        # adjacency disappears from the durable timeline.
                        if not text and tool_calls:
                            text = f"tool calls: {tool_calls}"
                        if not text:
                            continue
                        tool_name = str(message.get("tool_name") or "")
                        prefix = (
                            f"tool[{tool_name}]"
                            if role == "tool" and tool_name
                            else role
                        )
                        message_id = str(message.get("id") or position)
                        message_timestamp = float(
                            message.get("timestamp") or 0
                        )
                        saving = (
                            _take_context_saving(
                                tool_savings,
                                session_id,
                                tool_name,
                                message_timestamp,
                            )
                            if role == "tool" and tool_name
                            else None
                        )
                        for index, piece in chunk_text(text):
                            canonical = f"{session_id}:{message_id}:{index}"
                            locator = (
                                f"hermes-session:{session_id}#message={message_id}"
                            )
                            if profile_name != "default":
                                canonical = f"{profile_name}:{canonical}"
                                locator = (
                                    f"hermes-session:{profile_name}:{session_id}"
                                    f"#message={message_id}"
                                )
                            yield Document(
                                record_id=stable_id(
                                    source.kind,
                                    source.name,
                                    canonical,
                                ),
                                source_name=source.name,
                                kind=source.kind,
                                title=title,
                                content=f"{prefix}: {piece}",
                                locator=locator,
                                metadata={
                                    "profile": profile_name,
                                    "session_id": session_id,
                                    "message_id": message_id,
                                    "sequence": int(message.get("id") or position),
                                    "message_position": position,
                                    "role": role,
                                    "tool_name": tool_name,
                                    "tool_call_id": str(
                                        message.get("tool_call_id") or ""
                                    ),
                                    "tool_calls": tool_calls,
                                    "timestamp": message_timestamp,
                                    "session_started_at": float(
                                        session.get("started_at") or 0
                                    ),
                                    "session_ended_at": float(
                                        session.get("ended_at") or 0
                                    ),
                                    "model": str(session.get("model") or ""),
                                    "provider": str(
                                        session.get("billing_provider") or ""
                                    ),
                                    "source": str(session.get("source") or ""),
                                    "parent_session_id": str(
                                        session.get("parent_session_id") or ""
                                    ),
                                    "context_mode_bytes_saved": int(
                                        metrics.get("bytes_saved") or 0
                                    ),
                                    "context_mode_blocks": int(
                                        metrics.get("blocks") or 0
                                    ),
                                    "context_mode_tools_saved": str(
                                        metrics.get("tools_saved") or ""
                                    ),
                                    "context_mode_saving_id": int(
                                        (saving or {}).get("id") or 0
                                    ),
                                    "context_mode_original_bytes": int(
                                        (saving or {}).get("original_bytes") or 0
                                    ),
                                    "context_mode_saved_bytes": int(
                                        (saving or {}).get("saved_bytes") or 0
                                    ),
                                    "context_mode_sandbox_path": str(
                                        (saving or {}).get("sandbox_path") or ""
                                    ),
                                    "context_mode_saving_timestamp": str(
                                        (saving or {}).get("ts") or ""
                                    ),
                                    "chunk_index": index,
                                    "content_hash": content_hash(piece),
                                },
                            )
        finally:
            export_path.unlink(missing_ok=True)


def iter_documents(source: SourceConfig, settings: Settings) -> Iterable[Document]:
    if source.kind == "skills":
        return iter_skills(source)
    if source.kind == "workflows":
        return iter_workflows(source)
    if source.kind == "context_mode":
        return iter_context_mode(source)
    if source.kind == "hermes_sessions":
        return iter_hermes_sessions(source, settings)
    if source.kind == "references":
        return iter_references(source)
    raise ValueError(f"unsupported source kind: {source.kind}")


def skill_catalog(sources: list[SourceConfig]) -> dict[str, tuple[SourceConfig, Path]]:
    catalog: dict[str, tuple[SourceConfig, Path]] = {}
    for source in sources:
        if not source.enabled or source.kind != "skills" or not source.path.is_dir():
            continue
        for path in _iter_skill_paths(source.path):
            logical_path = path.absolute()
            canonical_path = path.resolve()
            if not canonical_path.is_file():
                continue
            catalog[_skill_id(source, logical_path)] = (source, canonical_path)
    return catalog


def workflow_catalog(sources: list[SourceConfig]) -> dict[str, tuple[SourceConfig, Path, str]]:
    catalog: dict[str, tuple[SourceConfig, Path, str]] = {}
    for source in sources:
        if not source.enabled or source.kind != "workflows" or not source.path.is_dir():
            continue
        for directory, workflow_type in _WORKFLOW_DIRECTORIES.items():
            root = source.path / directory
            if not root.is_dir():
                continue
            for path in root.rglob("*"):
                if not _is_workflow_file(path):
                    continue
                safe_path = _safe_resolve(path, source.path)
                catalog[_workflow_id(source, safe_path)] = (
                    source,
                    safe_path,
                    workflow_type,
                )
    return catalog


_MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
_TEXT_RESOURCE_SUFFIXES = {
    ".md", ".mdx", ".txt", ".rst", ".json", ".jsonl", ".toml", ".yaml", ".yml",
}


def skill_bundle_files(source: SourceConfig, skill_path: Path) -> tuple[list[Path], list[dict[str, int | str]]]:
    """Return canonical instructions plus referenced text and a resource manifest.

    Supporting material is followed only through relative Markdown links and
    remains inside the cloned source repository. Executables and binary assets
    are listed for the agent but are not injected into context.
    """
    skill_path = skill_path.resolve()
    skill_root = skill_path.parent
    queue = [skill_path]
    selected: list[Path] = []
    seen: set[Path] = set()
    while queue:
        current = queue.pop(0)
        if current in seen or not current.is_file():
            continue
        seen.add(current)
        selected.append(current)
        if current.suffix.lower() not in _TEXT_RESOURCE_SUFFIXES:
            continue
        text = current.read_text(encoding="utf-8", errors="replace")
        for raw_target in _MARKDOWN_LINK.findall(text):
            target_text = raw_target.split("#", 1)[0].strip()
            if not target_text or "://" in target_text or target_text.startswith(("/", "~")):
                continue
            target = (current.parent / target_text).resolve()
            allowed = False
            for root in (skill_root, source.path.resolve()):
                try:
                    target.relative_to(root)
                    allowed = True
                    break
                except ValueError:
                    continue
            if not allowed:
                continue
            if target.is_file() and target.suffix.lower() in _TEXT_RESOURCE_SUFFIXES:
                queue.append(target)

    resources = []
    for path in sorted(skill_root.rglob("*")):
        if not path.is_file() or any(
            part in {".git", ".retrieval-archive", "node_modules", ".venv"}
            for part in path.parts
        ):
            continue
        resources.append(
            {
                "path": str(path),
                "relative_path": path.relative_to(skill_root).as_posix(),
                "bytes": path.stat().st_size,
            }
        )
    return selected, resources
